add_newline = true

[character]
error_symbol = "[λ](fg:red)"
success_symbol = "[λ](fg:purple)"

[directory]
fish_style_pwd_dir_length = 1
format = " in [$path]($style)[$read_only]($read_only_style) "
truncation_length = 1

[gcloud]
disabled = true

[hostname]
disabled = false
format = "on [$hostname](bold green)"
ssh_only = false

[kubernetes]
disabled = true

[memory_usage]
disabled = true
style = "bold dimmed green"
symbol = " "
threshold = -1

[nix_shell]
disabled = false
heuristic = true

[username]
disabled = false
format = "[$user]($style) "
show_always = true
style_root = "red bold"
style_user = "blue bold"